### ISSUE TITLE
issue building release with new blobs

### ISSUE THREAD

**Issue by wbean1** [cloudfoundry-community/collectd-boshrelease#15]
Trying to build the new release with bosh, it fails:
```
# bosh create release
Syncing blobs...
collectd/collectd-5.7.1.tar.bz2 downloading 1.7M (0%)
RSA 1024 bit CA certificates aredownloading 1.7M (1%)
/usr/local/rvm/gems/ruby-2.1.7/gems/blobstore_client-1.3262.24.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:38:in `check_sha1': sha1 mismatch expected=bc77d2493b26e5c38e167a8a44fedfe287742c09 actual=173003d00e2fe95ac99e217668c44392c9525e2b (Bosh::Blobstore::BlobstoreError)
```
I'm not really sure how to dissect this release...  The expected sha1 seems to come from `config/blobs.yml`, but I don't see the source location for that guy specified anywhere... In `releases/collectd/collectd-2.1.0.yml` there is:
```
packages:
- name: collectd
  version: f1eb5a60a7eebc2e182b8a42761bc282108d4f64
  fingerprint: f1eb5a60a7eebc2e182b8a42761bc282108d4f64
  sha1: e0999c521e7c45a61b79c678cccfa59e7d533308
```
which in `.final_builds/packages/collectd/index.yml` maps to:
```
  f1eb5a60a7eebc2e182b8a42761bc282108d4f64:
	    version: f1eb5a60a7eebc2e182b8a42761bc282108d4f64
	    blobstore_id: e69cf0e4-cfc3-4d0f-7d55-88afe3f195ef
	    sha1: e0999c521e7c45a61b79c678cccfa59e7d533308
```
when I try to curl that blob out of the s3 bucket, i get:
```
# curl http://collectd-boshrelease.s3.amazonaws.com/e69cf0e4-cfc3-4d0f-7d55-88afe3f195ef
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>8D71B6458648E57F</RequestId><HostId>sxcrDOewzBmqcCt8ZpAsMdZQAoTdmq1ZAoHnsrxG0U64qXTb0oaXI/cruuOntFN5TJEg10rP/zU=</HostId></Error>
```
