### ISSUE TITLE
Usage setup 

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-community/collectd-boshrelease#5]
Hi,
I was trying to understand and use the collectd setup for an existing Cloud Foundry installation. Looking at the repository I have a few questions. I my setup collectd should report the data via the network plugin to influxdb. So the questions are:
1. Do I really need the collectd instances (2 of them) and the collectd_leader?
2. If not is it enough to just use the basic setup upload the release, compile it and add the property configuration to my existing CF deployment?

Thanks a lot for your help. I will try to help and improve the documentation. :-)

Regards,
Johannes

**Comment by poligraph** [comment]
Actually don`t need collectd separate server instances
just add following configuration in collectd-boshrelease/jobs/collectd/templates/collectd.d

```
LoadPlugin network
<Plugin network>
        <Server "x.x.x.x" "25826">
                SecurityLevel None
        </Server>
</Plugin>
```

**Comment by jhiemer** [comment]
@poligraph I am trying to add the current setup to an existing Openstack deployment. What I did, is I created an infrastructure file for Openstack

``` yml
meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: collectd1
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
```

I also changed the make_manifest

``` bash
#!/bin/bash

set -e

template_prefix="collectd"
STEMCELL_OS=${STEMCELL_OS:-ubuntu}

infrastructure=$1

if [ "$infrastructure" != "aws-ec2" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "openstack" ] ; then
  echo "usage: ./make_manifest <aws-ec2|warden|openstack>"
  exit 1
fi

shift

BOSH_STATUS=$(bosh status)
DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')
DIRECTOR_CPI=$(echo "$BOSH_STATUS" | grep CPI | awk '{print $2}')
DIRECTOR_NAME=$(echo "$BOSH_STATUS" | grep Name | awk '{print $2}')
NAME=$template_prefix-$infrastructure

if [[ $DIRECTOR_NAME = "warden" ]]; then
  if [[ $infrastructure != "warden" ]]; then
    echo "Not targeting bosh-lite with warden CPI. Please use 'bosh target' before running this script."
    exit 1
  fi
fi

if [[ $infrastructure = "aws-ec2" ]]; then
  if [[ $DIRECTOR_CPI != "aws" ]]; then
    echo "Not targeting an AWS BOSH. Please use 'bosh target' before running this script."
    exit 1
  fi
fi

if [[ $infrastructure = "openstack" ]]; then
  if [[ $DIRECTOR_CPI != "openstack" ]]; then
    echo "Not targeting an OpenStack BOSH. Please use 'bosh target' before running this script."
    exit 1
  fi
fi

function latest_uploaded_stemcell {
  echo $(bosh stemcells | grep bosh | grep $STEMCELL_OS | awk -F'|' '{ print $2, $3 }' | sort -nr -k2 | head -n1 | awk '{ print $1 }')
}

STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}
if [[ "${STEMCELL}X" == "X" ]]; then
  echo
  echo "Uploading latest $DIRECTOR_CPI/$STEMCELL_OS stemcell..."
  STEMCELL_URL=$(bosh public stemcells --full | grep $DIRECTOR_CPI | grep $STEMCELL_OS | sort -nr | head -n1 | awk '{ print $4 }')
  bosh upload stemcell $STEMCELL_URL
fi
STEMCELL=${STEMCELL:-$(latest_uploaded_stemcell)}

templates=$(dirname $0)
release=$templates/..
tmpdir=$release/tmp
....
```

As I don't need any further instances and just need to send the data to an existing endpoint, my jobs.yml looks as follows:

``` yml
meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

networks: (( merge ))

properties:
  collectd:
    hostname_prefix: cf.
    interval: 5
    config: |
      LoadPlugin "df"
      LoadPlugin "disk"
      LoadPlugin "cpu"
      LoadPlugin "load"
      LoadPlugin "network"
      <Plugin "network">
        <Server "X.Y.Z.W" "25828">
          SecurityLevel None
        </Server>
      </Plugin>
```

Based on that I did a deployment. Which was released and uploaded successfully. What I am currently struggeling with is, that I am not sure how do add the agents to my existing deployment:

``` bash
bosh releases
Acting as user 'vcap' on 'microbosh-openstack'

+----------+----------+-------------+
| Name     | Versions | Commit Hash |
+----------+----------+-------------+
| cf       | 222*     | 53014242+   |
| collectd | 1+dev.1  | 9ac68ae2+   |
+----------+----------+-------------+
(*) Currently deployed
(+) Uncommitted changes
```

**Comment by poligraph** [comment]
@jhiemer You need to add following to your stubs and jobs:

define collectd release in CF stub

```
releases:
- name: cf
  version: "222"
- name: collectd
  version: "latest"
```

and define collectd job in templates/cf-jobs.yml

for example for DEA 

```
  dea_templates:
  - name: dea_next
    release: (( meta.release.name ))
  - name: dea_logging_agent
    release: (( meta.release.name ))
  - name: metron_agent
    release: (( meta.release.name ))
  - name: consul_agent
    release: (( meta.consul_templates.consul_agent.release ))
  - name: collectd
    release: collectd
```
